Repository MarcelCoding/bszet-vplan, pull requests merged in 2021-09, with the labels that each got.

#1 changing port to 443
  src/index.ts
  src/utils.ts
Labels: size/XS

#4 added timetable
  src/timetable.ts
Labels: size/M

#7 Updated physik
  src/timetable.ts
Labels: size/XS

#10 Timetable IGD20
  src/domain.ts
  src/timetable/igd20.ts
  src/timetable/index.ts
Labels: size/L
