Repository MarcelCoding/bszet-vplan, pull requests merged in 2022-09, with the labels that each got.

#143 Changed room of LF 8+10 for IGD21
  src/timetable/igd21.ts
Labels: size/XS

#142 Changed BK2 to BK for IGD21
  src/domain.ts
  src/timetable/igd21.ts
Labels: size/XS

#141 Updated timetable for IGD20
  src/domain.ts
  src/timetable/igd20.ts
Labels: size/M

#147 Made BK-alias lower case, added alias for lf8
  src/domain.ts
Labels: size/XS

#145 Switched LF_7_10 to LF_10 to reflect timetable changes
  src/domain.ts
  src/timetable/igd21.ts
Labels: size/XS

#150 Added IGD22 timetable
  src/domain.ts
  src/timetable/igd22.ts
  src/timetable/index.ts
Labels: size/L
